#!/bin/bash

APPIMAGE="$1"
OUT="$2"
#SIZE="$3"
# Forcing the size to 52x52 prevents frame injection (at least on Cinnamon)
# However it affects thumbnail quality (it's just a hack)
SIZE=52

export TARGET_APPIMAGE="$APPIMAGE"

tmpdir="$(mktemp -d)"
pushd "$tmpdir"

icon_path=".DirIcon"

while : ; do
	# NB: make sure "appimageruntime" in in your $PATH,
	#     otherwise download it here: https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_64
	appimageruntime --appimage-extract "$icon_path"
	icon_path="$(readlink "squashfs-root/$icon_path")"
	[ -z "$icon_path"  ] && break
done

convert squashfs-root/.DirIcon -resize "$SIZE" png:"$OUT"
rm -r squashfs-root

popd
